# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-12 18:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20170312_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='user',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
